### PR TITLE
Configs used instead of command line arguments

### PR DESCRIPTION
**Pull request by mustafa1728**
- [x]  add all required parameters in configs
- [x] make config yml files for training and testing
- [x] fix bug in training caused because of configs
- [x] remove redundant scripts and other files to cleanup

### CODE REVIEW

**Comment by xianyuanliu** [comment]
Have you fix the problem with the performance you asked for before?

**Comment by mustafa1728** [comment]
> Have you fix the problem with the performance you asked for before?

No I haven't been able to work on that. I was focussing on first making the code a bit more readable and compatible with pykale's structure, so it also becomes easier to debug/test.

Regarding the problem, I suspect that it is a small, well-hidden bug (I may have used test features with validation labels, though not entirely sure), and will start working properly on it soon.

**Comment by xianyuanliu** [comment]
> > Have you fix the problem with the performance you asked for before?
> 
> No I haven't been able to work on that. I was focussing on first making the code a bit more readable and compatible with pykale's structure, so it also becomes easier to debug/test.
> 
> Regarding the problem, I suspect that it is a small, well-hidden bug (I may have used test features with validation labels, though not entirely sure), and will start working properly on it soon.

We can have a chat tomorrow if need, especially if you are not clear about your work or PyKale. Btw, which is the most convenient way to contact you? FB Message? Google or Skype?

**Comment by mustafa1728** [comment]
> We can have a chat tomorrow if need, especially if you are not clear about your work or PyKale. Btw, which is the most convenient way to contact you? FB Message? Google or Skype?

Yes, that would be really helpful. Skype works fine for me.

**Pull request merged**
